// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Ozzjyoz2BxI4cN3pFu9_KvIKPQsESSY',
    appId: '1:5809387071:web:036e3ab8342f509ddc2a8a',
    messagingSenderId: '5809387071',
    projectId: 'newfirebase-feedc',
    authDomain: 'newfirebase-feedc.firebaseapp.com',
    storageBucket: 'newfirebase-feedc.appspot.com',
    measurementId: 'G-7DYRRJKD5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_aIcM8n4qDz7ZiOsOLEQpadAyiUhR3w',
    appId: '1:5809387071:android:94652e8b53a3e6a7dc2a8a',
    messagingSenderId: '5809387071',
    projectId: 'newfirebase-feedc',
    storageBucket: 'newfirebase-feedc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3eRB8MknOY4Nya3wK41DnZh9ud5ug0Gc',
    appId: '1:5809387071:ios:cc928e95d5a86deddc2a8a',
    messagingSenderId: '5809387071',
    projectId: 'newfirebase-feedc',
    storageBucket: 'newfirebase-feedc.appspot.com',
    iosClientId: '5809387071-nf6194fdod1t29ceq3j9miu6q4c7m4ru.apps.googleusercontent.com',
    iosBundleId: 'com.example.newfirebase',
  );
}
